name: Run Haeundae Code

on:
  workflow_dispatch:
    inputs:
      timeout-minutes:
        description: 'Timeout in minutes'
        default: '15'

jobs:
  run-code:
    runs-on: ubuntu-latest
    env:
      TIMEOUT_MINUTES: ${{ github.event.inputs.timeout-minutes }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libffi-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script 
        run: python haeundae.py

      - name: Deploy to Cafe24 Web Hosting via FTP
        run: nohup python deploy_script.py &
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          pythonLocation: /opt/hostedtoolcache/Python/3.11.3/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.3/x64/lib
          TIMEOUT_MINUTES: ${{ env.TIMEOUT_MINUTES }}
